name: Build adocs

on:
  push:
    branches:
      - master

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get build container
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -v README.adoc -D public"

      - name: Rename file
        run: |
          cp public/README.html public/index.html

      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: "${{ secrets.ACTIONS_GH_PAGES_TOKEN }}"
          publish_branch: gh-pages
          publish_dir: ./public